apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8up
  namespace: flux-system
spec:
  interval: 24h
  url: https://k8up-io.github.io/k8up
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: k8up
      # /!\ Always upgrade CRDS before upgrading helm release
      # https://github.com/k8up-io/k8up/tree/master/charts/k8up
      version: "4.8.6"
      sourceRef:
        kind: HelmRepository
        name: k8up
      interval: 1h
  releaseName: k8up
  targetNamespace: k8up-system
  values:
    k8up:
      timezone: Europe/Paris 
