---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup-supervision-files
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: minio-creds
      key: restic-password
    s3:
      endpoint: https://ohara.infrao.top:9004
      bucket: supervision-backup/supervision/
      accessKeyIDSecretRef:
        name: minio-creds
        key: ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: minio-creds
        key: ACCESS_SECRET_KEY
  backup:
    schedule: '45 3 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
  check:
    schedule: '0 3 * * 1'
  prune:
    schedule: '0 3 * * 0'
    retention:
      keepLast: 5
      keepDaily: 2