apiVersion: v1
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:KXc+ZfSxzPbnNTkS4/ixQy0Z,iv:gq+bvhq9+coNh4vahsw+uXr0F/IVDLX9rtJp87q1H68=,tag:Ann2Mw86nHvcwyWhzlPn5g==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:XFR+Yw1aQqk36QacOdxCpvxzy6V+BPHwmYa0KUjCWoTsfhxHYtVuIo4yXloFhvScMqSYIqh73owDjHt4BgAmGg==,iv:swljMJIwjRYQanUsWlVEVjpRQTkn9k301COXUq3iO7M=,tag:DBVf7SWar7E0MFtnsLA+Ag==,type:str]
  restic-password: ENC[AES256_GCM,data:daDPqhBFqxezie72RyWhQHusHVU=,iv:UWmz+b51BxNu9xpxWVEfSVfhl6b2vu/4ljAx7W9cDaw=,tag:PyLN5SPiNzisrB42v/y+jQ==,type:str]
kind: Secret
metadata:
  name: minio-creds
  namespace: supervision
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVmRXOTU1UTRmMitzKzBk
        UmhsRjBwUUk4NnkwMjJHdG1KL1RyMFlwMmg4CkdDQTkxYTd1SEl0cGFwUExObjY1
        OU56RGdCSUk1b3huY2JrQk0yS3NObTQKLS0tIDNJbUhjaU9XUmEyWVNCemtCek40
        UzUyZEwzSGZTRUc2RVNWVXE4QWIrZ28KLGuqHItQPZzoXgmXz1syL1Vu2eSn8WBV
        KOIoGDKIKoAGct1/ixWrPPEUjM8XMJNY61pOlTTpearc4qI7s+Tx8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T16:14:51Z"
  mac: ENC[AES256_GCM,data:PL5t+2h2aKJizqUwJebMcz+HZ5cC+zwOQLu49oPmvTekC14hXy1sV/OlAlDOY8KfWYl/eXBfRsdk+wwsMeZtgKS8qDM6KOf5qmCMk5uekwIHabOqYrSGT70bKADn4Kb1u7bfAN/76+EXf4T2bSVLmYpXKu/eHbxC63PLNuM6DgY=,iv:Qv5qfr3dLoHV5+FAwPaJKGWYhSc8Cb6FlG0cqbi50Uo=,tag:0i+4MRZJrrryGjFVs+E8eQ==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
