apiVersion: v1
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:aogvip0UnGk0mjzemMxAORw+HvKGcXanEoc=,iv:Eoalf8d7/wzhw3sSOBmIKLOqaBs5ZjuVfO4ltDCoTCA=,tag:QIX15mVy5UFfF0WV4UZBJw==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:DNO1c5F7BC5WJAvsCxzLNm+wYB0wQxROkiv0fnoBbdmBfTA6qfmIe8AVyEAp3dpkjadeYhUOzuRQQw6WFc0YaQ==,iv:IW0AETQJpLEpXpOB01Yy+Ak0LEbshP3Av5bzgjxLyPQ=,tag:PJezc5v7cMZoDAqZt7bg7w==,type:str]
  restic-password: ENC[AES256_GCM,data:+bQm3qBQWngdzJCicMx3gBqtEa4=,iv:l140CCXFsPBHsoeLyJwGmWLyD2ueo0zyUeSUKSjN36g=,tag:FlXtQzmAQoHwbD+SPU2T0A==,type:str]
kind: Secret
metadata:
  name: garage-creds
  namespace: supervision
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGS2lSc3pXajgxMXNJMEdF
        blliMzVVUkxzbUdTaUhLcXpUM0tyVG80QkdjCkpmdFBTU0E2WDNpdThndlZNVlU2
        alBndTc5UkNCYXZtOStnamxkZmphcEkKLS0tIGRLY1BGcUZ2Sk1aZkwrQ1NrRDlz
        bmtvUWRpcDBrME9teUlGSU1tZ2U0b00Kaf1hj+z6OzNrhc6eI3/+IaDvi6mdsIlk
        218ZiRcAVp1uKS5Q/24w0f332ejqyVcVWMxsp+U/osJy8HesC4ngHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T20:21:32Z"
  mac: ENC[AES256_GCM,data:1lXgVusD3RUaLumrTp0cQ0yOdtN0DRs6MOVA/b0NHLJ/virfex+EP/mCABd9l9kWlZkzJpBVP5ioQ24i78HYUdBGT2VfKixXlIaHKXo4NpMUzIc3f3JqES0f9e5H+qygSG+3BCTC3EOMcP3vbloJj16uuVnmDDiosut+6Jo9Ce8=,iv:8hnf3pcKyQczkw7e/iYuoS4Kz8F2/qJaSdSsUEk2Iw4=,tag:2RfatpffS61fHBG10FtwiQ==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
