---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beszel
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: beszel
        image: henrygd/beszel:0.15.3
        volumeMounts:
          - mountPath: /beszel_data
            name: data
        env:
          - name: APP_URL
            value: https://beszel.egghead.infrao.top
          - name: DISABLE_PASSWORD_AUTH
            value: "true"
          - name: USER_CREATION
            value: "true"
          - name: TZ
            value: Europe/Paris
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: beszel-data
        service: 8090
        ingress:
          domain: beszel.egghead.infrao.top
        pvc:
          - name: beszel-data
            backup: false
