apiVersion: v1
stringData:
  KEY: ENC[AES256_GCM,data:STOIdG7HJ//3cnUHIUxXHl1EGol26BnOEH/MhcMq2c2n4yMPGNcDCqwudEe09goHcg+O3aeQ3b/BdH/DpvLnfFKHqlkjUjy0dyWXvmjyELI=,iv:q8uHLvjBwxhikV4maG07/qW8OjSMsCgEPNj7iq912X8=,tag:i/nhKqP6TV0kuesZuQhFqA==,type:str]
  TOKEN: ENC[AES256_GCM,data:nUm2+NdzVNgBzLSLqyJuxYRh3MxfnDr4uisqPlqulJvMAc3o,iv:GR1xBzl/HoWokqXqKRtaQCMoNyH5cGnIKI1x39bA9AA=,tag:sdKoDmPOzummMoX46rTTgw==,type:str]
kind: Secret
metadata:
  name: beszel-agents
type: Opaque
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cDlLRnVaZzhQcUI2c3Fi
        MHEyTHUxUzRWRnBlekdtdHpnMStPVEdaazFFCndJUk5MeEtVY3Y4U0RvUERXdDRX
        UEZyTVl4YUMxdklSTVF4ajFYaDdZU1kKLS0tIFYxWjlpajlhRmQzN2lKRTJOa0Fm
        SjdIb243S1UwL0syaEp1NnYxQmN0b0EKdNxfAMgcKEEA0HsvdnfeZ1dNN6RYj8Nf
        0Q1MHVdPExbcjWLIaXo2US0qdNB7hCw6asW95/ugoO0mDa1YLePVFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-17T17:35:26Z"
  mac: ENC[AES256_GCM,data:v3thaxrOgw9zro9jBucPcE99NesKFanyQh/X6fc6IMztJ8ToIis+VbtLY+hWWJaYlSXMEl6i45pD+2HL444h2f6Yw3k0t+cO/AgPUeZj6fCX+ouNmjIJedIarnJDTUsm2yuEnoYOyp2a25IX5+3i5iXi36CDtXZaWZ5NpG/h6yw=,iv:AebFblm3kew+/xqZEXKlmqzkFV5fjEFCbZytjxBC/R4=,tag:YGULAIs+4SxKUFRHPaYV/A==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
