apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
spec:
  selector:
    matchLabels:
      app: beszel-agent
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      containers:
        - env:
            - name: HUB_URL
              value: "https://beszel.egghead.infrao.top"
            - name: LISTEN
              value: "45876"
            - name: KEY
              valueFrom:
                secretKeyRef:
                  key: KEY
                  name: beszel-agents
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: TOKEN
                  name: beszel-agents
          image: henrygd/beszel-agent:0.13.2
          imagePullPolicy: Always
          name: beszel-agent
          ports:
            - containerPort: 45876
              hostPort: 45876
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
