apiVersion: v1
stringData:
  pluginSecret: ENC[AES256_GCM,data:hStCTaEk4hFZbhG4TMoSWOlje9Rk0+yWz1BT3ui0hBY=,iv:s/KVIqdhZ8OnkF2z3zoJSL8pygc5ELR+gH1mVys3UTo=,tag:huQiid9QGsW7VWmvfVfjXQ==,type:str]
  providerClientId: ENC[AES256_GCM,data:lzbwgX7SxqeqMH/0N2RpvYJH0aVlkY4c2xTvCXLWPW2cLPsu,iv:DXorTtRPrOZtNxVw0vtS04jlv7MS0c03ape+w6+QudA=,tag:pavhbdkomo1ygTRMI8YLpw==,type:str]
  providerClientSecret: ENC[AES256_GCM,data:2+n0lXoYQ0/NmKx0yY/PmE8HAPSjs6DCBSr0PSv+qGQ=,iv:jwlG6fVYWd19XLOkiJh7Z4IGdakfoK2Sf8+eybvns/s=,tag:s/kd9cGPZFshPW4h7K2agA==,type:str]
kind: Secret
metadata:
  name: prometheus-oidc-secret
  namespace: ingress
type: Opaque
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySDFjQUFRbXE5OGN0a0ZY
        SFVuTGU3QmNDTnhheHVOTkZNWE5yaGhMTW1zCis2Z09ha2hncmx5MmNNa1RUVE44
        L0hueFJIVG9xYTFmUVRrbFdxVWplb3MKLS0tIGcrVWVxRHNTT3QxZGw0bTBzMUNs
        VGk4VUw1Y2tmOHp3Tm9qSjZDWm1jQ1kKs6MLcRhL3j8aQqoNnwdf6ql0Wq2RUCEK
        ORRAc/O0IIqfy7CGrWEFtK57YUywL2agueSrGipIBAMiuuoR3It9Bw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T10:17:18Z"
  mac: ENC[AES256_GCM,data:SqYSh0OR68JgFHfQf1dIK7ifZxN9N0tg6GuxV+HFHOF3j0VfL138yiq3Ag5Rt2bQRjUa9zcQmhllq/QbTIhbFT6Xya9mULDZxPQyyHQZ3YGGB9DzdFoFXj4jT5p+8UR9ZjHaDEUGxjbegnQ8ivp93q4b8BWdT1YW8jezNUIKAoo=,iv:Ipl8rpyrowkAuid5LlI8HeYGVoOFcwIRXjVSrAFKsfE=,tag:NXsqPdeNi2OcDm4R0Qu8ZA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
