---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuma
  template:
    metadata:
      labels:
        app: kuma
    spec:
      containers:
        - name: kuma
          image: louislam/uptime-kuma:1.23.16-alpine
          env:
            - name: DATA_DIR
              value: /app/data
            - name: TZ
              value: Europe/Paris
          volumeMounts:
            - mountPath: /app/data
              name: uptime-kuma-data
      volumes:
        - name: uptime-kuma-data
          persistentVolumeClaim:
            claimName: uptime-kuma-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kuma
spec:
  selector:
    app: kuma
  ports:
    - protocol: TCP
      name: web
      port: 3001
      targetPort: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
spec:
  ingressClassName: traefik
  rules:
  - host: uptime.egghead.infrao.top
    http:
      paths:
      - backend:
          service:
            name: kuma
            port:
              number: 3001
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - uptime.egghead.infrao.top
