---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kuma
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: kuma
        image: louislam/uptime-kuma:1.23.17-alpine
        env:
          - name: DATA_DIR
            value: /app/data
          - name: TZ
            value: Europe/Paris
        volumeMounts:
          - mountPath: /app/data
            name: uptime-kuma-data
        volumes:
          - name: uptime-kuma-data
            persistentVolumeClaim:
              claimName: uptime-kuma-data
        service: 3001
        ingress:
          domain: uptime.egghead.infrao.top
          oidc:
            BypassAuthenticationRule: >- 
              PathPrefix(`/status`) ||
              PathPrefix(`/assets`) || 
              PathPrefix(`/api/status-page/heartbeat/`) ||
              Path(`/icon.svg`)
            secretref: kuma-oidc-secret
        pvc:
          - name: uptime-kuma-data
            backup: false
