apiVersion: v1
stringData:
  pluginSecret: ENC[AES256_GCM,data:9SLUMnHCDBSdp0fikVKMoERSi3qhYxoz2euelu+78Uk=,iv:ccNLdHHzlkasWqWKGaqhTkIyMAlQVCklbN9HlJ05Xtc=,tag:bK/6YGQU3IOh7RwOpQ7aSg==,type:str]
  providerClientId: ENC[AES256_GCM,data:eA3iyBJqWkdaWQ/APwbMCulgmihY6hblCI0ahYYTbof1Ckof,iv:a218s4fsHxlgOcLXP3usguRBJLB6+wKfTGsSCklYaDw=,tag:OichG+8v9RLjt2s45FtpkA==,type:str]
  providerClientSecret: ENC[AES256_GCM,data:qbiS/nB/muETvqRHji71NS9NIXTUcgcQkdtAgb9xdSM=,iv:skjqTlIZT7imPjK7gqyo+35Yx+6WiMDsYRlEpdYzPgc=,tag:FLBJqkOPR2LqGX4fXa70CQ==,type:str]
kind: Secret
metadata:
  name: kuma-oidc-secret
  namespace: ingress
type: Opaque
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyKzRrZEJEWkt4WnZaajJJ
        VUFUVUp1bUgyQitFV3QyaEpWRHcyd1NKcUEwCiszWHVtTGpvUnE0aGplVnRUNWpL
        UXVlcVoxUHVpWjNVT0lzU2c2ci9QNGsKLS0tIE16TnNxOTNJcTZiRmE2SDJwRjZn
        TXluRnJYcHF0YnVSSlZZWXRZM1BpOEEK6J12KqgwEKMmYHj15+BZeOJYo/TmLdlY
        tFP7pir5gZznEo1cRZ02PHehk5IkVzOxUIc8J/nfLvgHLQChF7ddSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-21T16:52:53Z"
  mac: ENC[AES256_GCM,data:NSP8Noli8kPzYuSUdTZH2vbZBweJjGH81u5jC4CUzCizsRtyiLGAa1LoXVg2dwW1dGrT6KlwlYhPICSC3Nd1e8soWA/zUG71UmD58bhUjM+i0J7CUkILReMndQzq5AlDey1p/2sTb3avsYLVLsTWu5VkAEddOc/PgjZpbLbOFnA=,iv:2kNT4sGaHGdcRzFrS6FYm1WDrl66ieY0UWHQ+5FF4go=,tag:eIzEO9E6AzlCdAmOwn7FNw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
