---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-pushgateway
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/prometheus-pushgateway
  ref:
    tag: 3.4.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-pushgateway
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: prometheus-pushgateway
  values:
    serviceMonitor:
      enabled: true
      namespace: supervision
      additionalLabels:
        release: kube-prometheus-stack
