# templates/deployment.yaml
{{- range .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  {{- if .deploymentSpec }}
  {{- toYaml .deploymentSpec | nindent 2 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      {{- if .podSpec }}
      {{- toYaml .podSpec | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          {{- if .env }}
          env:
            {{- toYaml .env | nindent 12 }}
          {{- end }}
          {{- if .envFrom }}
          envFrom:
            {{- toYaml .envFrom | nindent 12 }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .containerSpec }}
          {{- toYaml .containerSpec | nindent 10 }}
          {{- end }}
      {{- if .volumes }}
      volumes:
        {{- toYaml .volumes | nindent 8 }}
      {{- end }}
      {{- if .imagePullSecret }}
      imagePullSecrets:
        - name: {{ .imagePullSecret }}
      {{- end }}

---
# svc generation
{{- if .service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      name: {{ .service | quote }}
      port: {{ .service }}
      targetPort: {{ .service }}
{{- end }}

---
# pvc generation
{{- if .pvc }}
{{- range .pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    k8up.io/backup: {{ ternary true false .backup | quote }}
  name: {{ .name }}
spec:
  accessModes:
  {{- if .localstorage }}
    - ReadWriteOnce
  storageClassName: local-path
  {{- else }}
    - ReadWriteMany
  storageClassName: nfs
  {{- end }}
  resources:
    requests:
      storage: 5Gi
---
{{- end }}
{{- end }}

---
{{- if .ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  {{- $middlewares := list }}
  {{- if .ingress.corspolicy }}
  {{- $middlewares = append $middlewares (printf "%s-%s-cors-header@kubernetescrd" $.Release.Namespace .name) }}
  {{- end }}
  {{- if .ingress.oidc }}
  {{- $middlewares = append $middlewares (printf "%s-%s-oidc@kubernetescrd" $.Release.Namespace .name) }}
  {{- end }}
  {{- if $middlewares }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ join "," $middlewares }}
  {{- end }}
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .name }}
            port:
              number: {{ .service }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .ingress.domain }}
---
{{- if .ingress.corspolicy }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .name }}-cors-header
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - {{ .ingress.corspolicy }}
    accessControlMaxAge: 100
    addVaryHeader: true
{{- end }}
---
{{- if .ingress.oidc }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .name }}-oidc
spec:
  plugin:
    traefik-oidc-auth:
      {{- if.ingress.oidc.BypassKey }}
      BypassAuthenticationRule: "${OIDC_BYPASS_KEY}"
      {{- else if .ingress.oidc.BypassAuthenticationRule }}
      BypassAuthenticationRule: {{ .ingress.oidc.BypassAuthenticationRule }}
      {{- end }}
      CookieNamePrefix: TraefikOidcAuth{{ nospace ( title .name ) }}
      CallbackUri: https://{{ .ingress.domain }}/oidc/callback
      Provider:
        # You could just write strings here for the values.
        ClientId: "urn:k8s:secret:{{ .ingress.oidc.secretRef }}:providerClientId"
        ClientSecret: "urn:k8s:secret:{{ .ingress.oidc.secretRef }}:providerClientSecret"
        Url: "https://pocketid.egghead.infrao.top/"
        UsePkce: false
      Scopes: ["openid", "profile", "email"]
      Secret: "urn:k8s:secret:{{ .ingress.oidc.secretRef }}:pluginSecret"
      SessionCookie:
        SameSite: strict
{{- end }}
{{- end }}
{{- end }}

---
# configmap generation
{{- range $name, $data := .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
data:
  {{- range $key, $value := $data }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}

---
{{- end }}
