apiVersion: v1
stringData:
  OIDC_BYPASS_KEY: ENC[AES256_GCM,data:SANQr8+sjOJyp+jSsb5yDzoBfeEB1xVBarQFcvnisCGwlbwm6fczdFRAQ2sCREYXCZMixCCqrHxiYPqMZAL05MHS1cbtPe7w7Np3Dx9sF0cI+z4s4FegjBAbIrYb6g==,iv:8iwlkNDnMCctXqIIICTtJPetpb1vZEweis4x0NQy/Sc=,tag:e4rsUQEsj9lmuyrCNiI/cQ==,type:str]
kind: Secret
metadata:
  name: traefik-secrets
  namespace: ingress
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHd1V1bzZ4ZU1udm9HU245
        SnFqVEt4RFFmOEdkcmVWMm1VZzdLODBGekgwCjQ0NThhY2FEVTllak5sczFaUi9X
        cys3UlFtWWFpTm1MdEtZbXRlckhZNWsKLS0tIFIwSjNtYmN4UjNtOXl6WHNCNXZa
        RzBYanFDeFlQdkZmdW9lVjB6STk5K2MKMxpwiMHoORJKVVq/BcVPRkQF5Y45et4g
        gSG8ozOBX3Ooit453UnDzkhwKcHLsJ5O0jlS8ICxNCLaa+iD3vO7gA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-27T19:52:48Z"
  mac: ENC[AES256_GCM,data:msTqzGIt+unfGRRp0qyuCrpn3XU4boRONObktPAkCv4f6n508AT6cQD9O6Xiob7RP5UfKcczXqOKzqghh7nCYsXXet81sPBhEM6JzuV+pK3laIMpE450OOdaYinmG7jjxjfIwgP6EotO0Pfbtx7OPYkpEFJckgUv+/plXyU4ElA=,iv:tJ0cXudBCMv1zM81sKSOBl9AXSw+fBWbXZl/jLhNE5M=,tag:TnlvSmeg0+P5589tqKKI+g==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
