apiVersion: v1
stringData:
  OIDC_BYPASS_KEY: ENC[AES256_GCM,data:D0zMrkWF/fkGTd+YcUOjzzK8iKKgQSltKIKi9xJNPkOelkGTVhGCyIb7YrEqRqG3o5KvNExwMDMDWXTaCe315npcCXiWbaivsBhrDfyMxEgUkA/CxKLlf9dubpGBZQ==,iv:DzMoa847Zv9/AaHb/UiHsiYd6155mRnPrCOJbLUzeos=,tag:VlwA02RveTzB/gQ2aNDnUQ==,type:str]
  pluginSecret: ENC[AES256_GCM,data:FrjfeCyppKcwb3uT9DI3d6D3xLy59+rF7j8JzpuCNA8=,iv:Jel6yw7rBHGv7Deu9t74+fTgaPBxBX2HtSFrDUkisI0=,tag:OcnhGmkfwWi8OQ3GSssXTg==,type:str]
  providerClientId: ENC[AES256_GCM,data:cHyRd5RLWq7oy1rbnjyFYjI9bSE0uRBrTOY/lVOdSFJgNCNa,iv:a/iou2vghdIECrz9U/KJeYW+ZoOD4fOHGaz7pZ88kVA=,tag:Tl9ZULx9FS4XCPFz91E6cg==,type:str]
  providerClientSecret: ENC[AES256_GCM,data:JGJcNmKOmcq+sgRDj7TIHW+UVuPrZbMs4h4uJ2S9CkA=,iv:WYEhOTHmIZadyzkQXb5iHHSmEC8jEIkXARiK/ImWUR8=,tag:iOBsZXBcMBoSJpSV6YdPVQ==,type:str]
kind: Secret
metadata:
  name: traefik-secrets
  namespace: ingress
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTlZyc1NSM2VyZ0d5MGxC
        MVJxMDVGZkgxZ2dpTTQ5bGE5bjd2QlAvQlJZCm9QSVA5MkxkVXdLVENzb0lzelox
        NHFncmQ5L04wYjhJUGUzSFFVK0V1ZDQKLS0tIEdxazdLYmVkbWJrV0VlaEl2Vllw
        bUJ2UlE2MHM3VEE2QjlsWVA2QzlQSm8KuMESX9ZW7+njLA2ZIc6FtqgxyO7ej2Dd
        T9kSmtUCH+ka29MxoAkUeyadQMgsLIlvri4Uo/rgXcGIlKgnEeOIxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T10:53:11Z"
  mac: ENC[AES256_GCM,data:DJmpu3DoEIpYxmyAM9gpJdSWwpegIqC9rwgmIxl8y5rkz136QWzAOXyJ/kkAXsNcc2JKz8T+X39ANSJhX3Yk6hMXPfhVteWALYef38qYkg2Dg/OBqENd/7Rz8wc/bg6H+xhmWwbx9b2ygCs7vSSVHTW9NOozZMyK9wUfzyeHLtE=,iv:nes76CXMgC3JQPBCrky8iUS3b5ENU+gNqxEfsjU9hfI=,tag:pXWb9OZ8ecseV9hdWwZmJg==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
