apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  install:
    createNamespace: true
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      version: 1.19.*
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 1h
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    crds:
      enabled: true
    dns01RecursiveNameserversOnly: true
    dns01RecursiveNameservers: "8.8.8.8:53,1.1.1.1:53"
    resources:
      limits:
        cpu: 25m
        memory: 60Mi
      requests:
        cpu: 1m
        memory: 55Mi
    extraEnv:
      - name: TZ
        value: Europe/Paris
    webhook:
      extraEnv:
        - name: TZ
          value: Europe/Paris
    cainjector:
      extraEnv:
        - name: TZ
          value: Europe/Paris
