apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  skypiea.server: |
    skypiea.infrao.top:53 {
        errors
        cache 30
        forward . 192.168.8.1
    }