---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: local-path-provisionner
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/rancher/local-path-provisioner/charts/local-path-provisioner
  ref:
    tag: 0.0.34
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisionner
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: local-path-provisionner
  releaseName: local-path-provisionner
  targetNamespace: kube-system
  values:
    storageClass:
      provisionerName: local-path