---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisionner-git
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/rancher/local-path-provisioner
  ref:
    tag: v0.0.32
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisionner
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: deploy/chart/local-path-provisioner
      sourceRef:
        kind: GitRepository
        name: local-path-provisionner-git
  releaseName: local-path-provisionner
  targetNamespace: kube-system
  values:
    storageClass:
      provisionerName: local-path