---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: local-path-provisionner
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/rancher/local-path-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisionner
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: deploy/chart/local-path-provisioner
      version: 0.0.32
      sourceRef:
        kind: HelmRepository
        name: local-path-provisionner
  releaseName: local-path-provisionner
  targetNamespace: kube-system
  values:
    storageClass:
      provisionerName: local-path