apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  interval: 24h
  url: https://starttoaster.github.io/nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "v4.0.*"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
      interval: 1h
  releaseName: nfs-provisioner
  targetNamespace: kube-system
  values:
    nfs:
      server: ohara.lan
      path: /mnt/raid/k3s
      mountOptions:
        - nfsvers=4.2
    storageClass:
      defaultClass: true
      reclaimPolicy: Retain
      name: nfs
      pathPattern: "${.PVC.namespace}/${.PVC.name}"
