---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo-runner-oci
  namespace: forgejo
spec:
  interval: 1h
  url: oci://codeberg.org/wrenix/helm-charts/forgejo-runner
  ref:
    tag: 0.6.20
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: forgejo-runner-oci
    namespace: forgejo
  values:
    extraEnvVars:
      - name: TZ
        value: Europe/Paris
    runner:
      config:
        existingInitSecret: act-runner-creds
        file:
          runner:
            capacity: 3
            envs:
              TZ: Europe/Paris
            labels:
              - node-24:docker://node:24-trixie-slim
              - nixos-latest:docker://nixos/nix