apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:aZtnHl6nhZHgtjxsPttkK2WgxZlPLXPNJlw22PaF8MWk4OXYDLC1fw==,iv:YCewqQcEjIAVXoyQLgIYWjuzatYpu2SyMm9VduBKw6c=,tag:C4n+mMbmGNR7u9TB5LQwiQ==,type:str]
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YVNmRWRORzdXdml4Sngz
        RkVRODQ2MW9HQWhJK3lTamRXbmNacHpJMzJjClpaOXpWeVlwVWF4dnNxVjgzc2ti
        QXlzMm1vc0dTS3hMRXhicmpIanJGYmsKLS0tIGVickJPMDdUWm45KzM4MnUvRUF6
        aXcydzNKdGN0c2Y1L0ZhUmFQMnhIblUKxuffT+1hUzAQFjU9jE29iDkwrMIgYCNZ
        2yv5rEuyBfeH4cX00e0c8YV/4jYJm9ELUusrfXior1Lti4lKByCW4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T20:51:02Z"
  mac: ENC[AES256_GCM,data:pzQhgRTk3Ho/mPr7xUkMyhM3tVVCkA2EfyYFQ5a0viLPkmOpPLV34Vc3yaFAc1hY4DXQ9ifsRic/56ahA4QYfI7dswywLaGzVQLtZlYkcZcIOQ6Rdq0nC587rTRDkY+Fv8bOAY7pmZducmlNiLZzozXpcF2o8UybITPziU8lkxA=,iv:ZeG9SioAf1/eBILIIO8KkBvdyemDQQtesngm3EtBwno=,tag:syc7WiOIZTn7obBPo1shZg==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
