apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:mRKhu+f4Kr4uun1hBfViElO2p7NtRLWDR3dwU5Q2uJmUDU/dN5ITLg==,iv:ngWXDnxjunHwWA/SKzVLkrVDXLxpA0tDkh4AkAe6L8I=,tag:QGRDIcp7RkRg+Q1MaRIkUQ==,type:str]
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YjBIMmlYUTNhSXlYb0tL
        UVUwM3J5OXZFREFxa04yQitYVjF3TTREcDM0CjM1Q0FqMjAxQVV4Vm10aWVhMm1p
        NVk2TGRaaVNXQlhEK25hSTBxaVdTNVkKLS0tIHFWSEJ3QmdkQVpleTI5OEdaemRq
        Y3MxSWxnN0RHY3ZKVFRsYlgzN0ZyOWsKNn/UmcvG4OZnpvTCZP65kyCCWX3vDHvi
        7VaytCYjmrnIm6ZABA0KxDvInFknsKwC+Juh9evCBHOPh4GkwulRVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T20:33:29Z"
  mac: ENC[AES256_GCM,data:vRvSMif3enuCIRTttmpPv86oWKdVgBfD9//i/MrOvCgJGjMCY/OGu42n6izSJd6ikTox9F0fQH0Qzbfg4EMkCp/Y8Emdc3gHuo+iVwi3wCz85X9xKyAykU2QKuOWL9rhyvjU3vb/i85OIel2fcJ8vDXIZYfscN0D93e3oSmgKDA=,iv:u7iWq4wMxO9UvEGQ11IJmiewvNx69nIHsKhKz6fCaYc=,tag:rJIgOnNVbI7s0X5Rt1jblA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
