apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:SLIeB5DZnm/Sxm7KI+S0WDRCfKms9igspyrP8fT5eFpEEJJkktbgaQ==,iv:9jtDpqJpqzwNVIAV+IPRLA+R3JNHeammuNyNdkj0Dgc=,tag:hO3OQcGCmOc6i8DC3dHwQA==,type:str]
  RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:Neanw5veC0KuuA5q5R09tSN6VEkhPU21IOcibsmZBllaxTSUxtTD+w==,iv:xunqNW2WfEzkMZ7imULZLajt6J2zEOvZwJfye7vFgZA=,tag:OR+LXpT7AlDzclNtMKLX2Q==,type:str]
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcU5uekU1SXY1cHR2ZVkr
        TmkzckVRaEk3L1NuQUd4RWk5KzlLaFZhZUIwCmMzaVlaeEdqbWZYTllEYStxSlVV
        MlJXU2lvSnRUVFpET1Z4QXp1UjJvZFUKLS0tIEphRjdCTGh0ejJhcVA1bFZIOEFh
        anJNQXE1d0FUUkNrRzZlYU9za2dra0EK20kL8mPApwoXpquyXwoGEoaQfSgV6H5C
        p5/rckx0NmYVYbIOUKuFUEd8199ln530vw4WBDxsnXwilYrTVNmkRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T21:18:13Z"
  mac: ENC[AES256_GCM,data:vwYZc2dgLwMaq6e23dqsjqIEZa+I0gPZh6rblXU6CXifol1lwp6KGuDqCbwjvaB2eZZIlspKCiGLmb0GiLuIXogpqhHqk6fpGUoaExzmqQzY+bAL7PlivlZkvG08Jng4sLMfr1P7ALfjduMbCsV1P4ZcSu8P3BU+S67CrbXyi/Q=,iv:ahGglOJPfWPUt53KqNmTOSMekLJlOv4q4xSSeBBamJk=,tag:dx1Ipqm4pdj9C4L1bp3Log==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
