---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-config
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: ohara.infrao.top
    path: /mnt/raid/arr-stack/config/deluge/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config
  namespace: media
spec:
  volumeName: deluge-config
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: ohara.infrao.top
    path: /mnt/raid/arr-stack/config/jellyfin/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
spec:
  volumeName: jellyfin-config
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrents
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: ohara.infrao.top
    path: /mnt/raid/arr-stack/media/torrents/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrents
  namespace: media
spec:
  volumeName: torrents
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: ohara.infrao.top
    path: /mnt/raid/arr-stack/media/media/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
spec:
  volumeName: media
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

