---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrents
  annotations:
    k8up.io/backup: false
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: ohara.infrao.top
    path: /mnt/raid/arr-stack/media/torrents/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrents
  namespace: media
  annotations:
    k8up.io/backup: false
spec:
  volumeName: torrents
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  annotations:
    k8up.io/backup: false
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: ohara.infrao.top
    path: /mnt/raid/arr-stack/media/media/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
  annotations:
    k8up.io/backup: false
spec:
  volumeName: media
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

