apiVersion: v1
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:UK7oGEl6+ZWIv0VVJ1skWT0M8HAOAFENH7M=,iv:9rtMplZTLPmjJnYlX8nNlf9uVeFUYhFX2GEFoibZbts=,tag:eZ46nEyDfMD9YKIr2T8Q6g==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Dmqkxk60Kn9bbkokto/vD4Fm93ChbVqF//XDKgMwnCEiMk6EpDdAwHYOnaL7Lh2tPx8Hf+dUvfyYx8sOn4H8OA==,iv:HP/O41dB35biK7fqaZgF7VLQd+0M9YRb4xnYcOR8wUQ=,tag:PKjaMR4wqRScQ7LAk467ag==,type:str]
  restic-password: ENC[AES256_GCM,data:LrTMvqWCqiiR0qJOWk3B1hCURyR7NwJKCFZEgnc69Ic=,iv:eCQ4AxwMmPGIJzWNqtQ7UbeQiBxohyZNHSpkdvQKu4Y=,tag:RfhsDjNwl4Y7EgtXS8dPnQ==,type:str]
kind: Secret
metadata:
  name: garage-creds
  namespace: media
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TmplaWFHQ2pBZURMSm9s
        UUJ4S0Y0RWRxeTFZTEY0YXV3TDlvWFRzb1YwCktidTFXa2F5ZlZqdVg4aklsNGRZ
        ZzRFR3JNeVdSalptUEFwK2Z0QW1YdFkKLS0tIFg4RUYvaExSRDBNRjlud0JYa0hD
        M2dHZkY1cHkrcTVWLzd4Si82RUFsZzAKz55caIPcx1UlfTOrKng1nZswss1aOTtk
        4NxChABlUEHQLWQQsWHlTujKTzdke9FbBFPL4DabOXK3l6LCYyoNMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T20:06:00Z"
  mac: ENC[AES256_GCM,data:sM2V+R26/vd7hgTbDC55J6Xy50kgdp1VBqXsewV3L6ci/+COGRGnmhXBPSngvkuanNwpUHj4/sDC3NYFr8Rl+c/yf09Vko3oGOh2LBbLcEi4dxKqFpdfkP0a1etGAdRGwqjXRuCNuEwNppj9YJtTbr8sziVbaWheU+yLCPjs1LU=,iv:zc3FeTE+0avmMcStdOh0wxirsBkaQByDv+FDs4vVzDE=,tag:1zhvR0kkFClLoiQWl571Tw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
