---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: arr-stack-files
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: minio-creds
      key: restic-password
    s3:
      endpoint: https://ohara.infrao.top:9004
      bucket: arr-stack-backup/media/
      accessKeyIDSecretRef:
        name: minio-creds
        key: ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: minio-creds
        key: ACCESS_SECRET_KEY
  backup:
    promURL: "http://kube-prometheus-stack-prometheus.supervision:9090"
    schedule: '0 3 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    podSecurityContext: # For many files restricted in all pvc
      runAsUser: 0
      runAsNonRoot: false
  check:
    schedule: '0 3 * * 1'
  prune:
    schedule: '0 3 * * 0'
    retention:
      keepLast: 5
      keepDaily: 2