apiVersion: v1
stringData:
  pluginSecret: ENC[AES256_GCM,data:RE9koA/XyYQEr4V34xiePh6X0QI58dCdCgcI/JY1Kys=,iv:eMsbDiX3vYTTCyT2oZ085F4Hc7hC1sj3A1HFqpaUiOo=,tag:iiTCTOIih3E3H6acZ9Dp3A==,type:str]
  providerClientId: ENC[AES256_GCM,data:jVDK4UBaha5lz3vTqTSPNnD+YjtXLAealAayytfuVvnoJVhn,iv:gGWaYl4D11/Nhdo7bymCMirb1u/CRj79Bh04bZadf58=,tag:+b2lF9k13/MBAJf6dH5vOw==,type:str]
  providerClientSecret: ENC[AES256_GCM,data:pr8zJ0ZudEPtQ+xHXRdWcpOlyAhQQwWYLH5mC1HbPEw=,iv:ZX29a9ch0i3sLqPJdamk+73xwWN4CDRyA48wGoLvfUM=,tag:D8NRmwqCU6akkQ0n87w+BQ==,type:str]
kind: Secret
metadata:
  name: deluge-oidc-secret
  namespace: ingress
type: Opaque
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMklzODRoWTZLSkRDM3NO
        c2UyZm1Hd2crVnhCY09YNzBvWFp6WVZTQUR3CmVRQlhkN2wvRWZkTVl1Q0xlVzBV
        aHZTQzVONW9YemxSaWN1K0ZMSmI2eHMKLS0tIE9rVG5IR0JPWVBDM214V25yRDNY
        UkVkeWo2bm5QMmtJeXg4UGRCVkJ1UzQKIdayB9Px/MPq3q16TZMrP4mtKymjaXEk
        rRCSfCcTUVeNDsBUuiPZjwOB5hemrdCaL3ewxUlw+FEJcUsvyemzoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-21T18:09:34Z"
  mac: ENC[AES256_GCM,data:rnAxHzUeniroExdbYveaF9MfEguNntLkZvZbZEw5QKxKcf60t19OxhwFvd4SzqaoOgBjVfxL40wX3Y6bbGFVm4tQLXExFs2CSwoK2p4MGPkWXGH2Xr7bAYEzjEdLKWzi6d6CNQceGeG9AFatxUDOLZ+9F13sdWZHInb7k9R2emU=,iv:yIxFAs1T0NVnD/wq57H9igf+77jw/bSafXUv/LlZMkY=,tag:5eeohOSj2qOlwMfHOBme4g==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
