---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: jellyfin
        image: jellyfin/jellyfin:10.11.6
        containerSpec:
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            seccompProfile: 
              type: Unconfined
          readinessProbe:
            httpGet:
              port: 8096
          livenessProbe:
            httpGet:
              port: 8096
              path: /System/Ping
          # resources:
          #   limits:
          #     cpu: "2"
          #     memory: 1Gi
          #   requests:
          #     cpu: 1000m
          #     memory: 500Mi
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /cache
            name: cache
          - mountPath: /data
            name: data
          - mountPath: /media
            name: media
            readOnly: true
          - mountPath: /dev/dri
            name: dri
        env:
          - name: JELLYFIN_PublishedServerUrl
            value: https://jellyfin.egghead.infrao.top
          - name: JELLYFIN_CACHE_DIR
            value: /cache
          - name: JELLYFIN_CONFIG_DIR
            value: /config
          - name: JELLYFIN_DATA_DIR
            value: /data
          - name: JELLYFIN_LOG_DIR
            value: /log
          - name: TZ
            value: Europe/Paris
        volumes:
          - name: cache
            emptyDir:
              sizeLimit: 8Gi
          - name: media
            persistentVolumeClaim:
              claimName: media
          - name: config
            persistentVolumeClaim:
              claimName: jellyfin-config
          - name: data
            persistentVolumeClaim:
              claimName: jellyfin-data
          - hostPath:
              path: /dev/dri
              type: Directory
            name: dri
        service: 8096
        monitoring: true
        ingress:
          domain: jellyfin.egghead.infrao.top
        pvc:
          - name: jellyfin-config
            localstorage: true
            backup: true
          - name: jellyfin-data
            localstorage: true
            backup: true
