apiVersion: v1
stringData:
  pluginSecret: ENC[AES256_GCM,data:WRRx0fnIYy7yfSr1FhpMlStaG8csITRAjjsSWs37tUY=,iv:4Uhgo0mgjSil6p76hPuTYFiXzB00VT67fugS43vfBlk=,tag:lToYZudmTtlPbNNmbYNsVg==,type:str]
  providerClientId: ENC[AES256_GCM,data:c2+uI4eWoKiQWMMBb0K9SQsAv4otgZqFzl386Iz91T43eUx2,iv:NUHNbD2Z3VgIS9v7eP81e8VYl/egA57AfZxWf6cJw+s=,tag:Rp8506Zq0U4XAggGCjDhHA==,type:str]
  providerClientSecret: ENC[AES256_GCM,data:pTCgVRdFKzQ4z5ZJOj+I19eQ6ifTpIk4ExMQ2eXgWOY=,iv:mXSyRc/FVZoZEgAU++bu/NSyYfHi2rX3bzNeavQiTbs=,tag:4gZ0RrnMquBhKkxNloQPag==,type:str]
kind: Secret
metadata:
  name: prowlarr-oidc-secret
  namespace: ingress
type: Opaque
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUE1BYVM3b3ZnTjQzek51
        VlJROWk3THcxZW1pZFVmeElBQVdQdXV4NWpRCnQ0UEp5MHNuQnRFRmI5R2ZTTXBs
        N1M4cUx0blVRdVg3QzExMjF1MkRiSlUKLS0tIFFnVXVFYk0zdlpWQkZaQTlsYXQy
        VWsyWkM3RlZ0cWJqc3ZGcEk5SFVjdmsK4lqWz3Swa3BV4pbxl2rvoy4frb5QDTJ2
        PDZ6MfzAIrhYi9xG2IE8GlXmGT8Cn0rIZxE69db1I549Yek4JSpIfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-26T20:25:02Z"
  mac: ENC[AES256_GCM,data:SGUDV1mr1sDazkWliMiHG3AHC25Ushf2rhiE2xzyTTg0z1gU5i0yNInGf3e8fNsHqFM1jbZHuQHe7VBayAcVnGlSE0086hcEyb9DtPxuOl+vm8sfeM6SQwwpyndM/nKzzJydAJ759DQPWSw9f85wNXKb+6bvRRgbkmNeSVMx5Lc=,iv:lhZvEOakCyN1bMseIpy/x/Q58qnjuDywH3pW11AyhuY=,tag:RrohMeRer6fkO0tXTGhQYA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
