apiVersion: v1
stringData:
  pluginSecret: ENC[AES256_GCM,data:leQ3DHATnAJhyWqDQ4UC2iEyJdwZUz3ebrvwwo8xu18=,iv:4818N0GE5tdARHWa9a8aWToCYPstyoql8HMPotTdYiw=,tag:sDQv81DwipGA96xIAmjT8w==,type:str]
  providerClientId: ENC[AES256_GCM,data:nwCQOC1xt8GiajpV60rk7unHfWK6Ec28ZlHxOlL6/nK1qU8U,iv:vrTF8E5Eocq+6n15n1hHDg1Uxd3WShawtLXnxDaHesw=,tag:Ck8dvdgqP7VgSVSEQdg91A==,type:str]
  providerClientSecret: ENC[AES256_GCM,data:ed8O5WKJif3b1HOCejJSsI70YsLgYaIIVJoCGwPFL8Q=,iv:92jQFErTGVDqrl5wu37lAuCz1W2NiycoeC2udsvSIxI=,tag:BX78x22Nz8E3l7dMqe5hKA==,type:str]
kind: Secret
metadata:
  name: radarr-oidc-secret
  namespace: ingress
type: Opaque
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWUNVdjhjcjFqNmR3REt6
        T0pSd2xKWE5jZVViN1ZpY3JNSFNzeVRQSnpjCnVzbzNYSTFDakxOVldoVXcwdTcx
        SENONE5MZm1lSjhvWmZyaUtwckp1RkUKLS0tIGc1RDJxU1VHV0F4Nk5GbTRmTUVl
        alRXS3RWWFJBeW1MWWJGWWUycHlKR1EKEdUhbX5ULjQYZOouNbaFy1jZGUehi1bs
        tyNSEbvcnVXuJ26mPs14rx+ol2vB0fK4RuF+X0Z6AIj0bFO8Si78Nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-26T20:07:13Z"
  mac: ENC[AES256_GCM,data:qA0+03zKUzD5c48KQ3f8H7LHmPkBxkHExjsF5/idFljcxECBA0xjAkG5J76rl17g4Eoh/j+8uA9+e0xsCG0a8U+hRGBQF4atGjDJOuYZf+WF6RraTK/oPWhFauheUDzA8p11LybnwA+3OkxCchDRMTODziWFy6WmvQjHF4zsZ28=,iv:u42Wr93MBsY+4ELEDQOzghe3iPxbUWmeTes4gHGvjDU=,tag:cojXGpRk7LYIDKto26kkjA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
