apiVersion: v1
stringData:
  pluginSecret: ENC[AES256_GCM,data:M4bf0ZPRGuttEJoF0kgcjpWR5sMrK0u2PXnFuNg+cFw=,iv:C/7kS4W/fUTJGj0k3ZVKX7Z28xYtwo6BxPqE5H2EeCs=,tag:anjJsvVGJV1/Hvjuny1Egw==,type:str]
  providerClientId: ENC[AES256_GCM,data:dP2ctRg2c1D6wGWBRc+qlN0DNmuQ2G0M9qilquBAEKCh8sjp,iv:dc3hezjGOxQDpsIkpSXWiC5gHhFggUzXHc5jhC1wt+s=,tag:NTN2HhD2ElHoGsaECy/kCA==,type:str]
  providerClientSecret: ENC[AES256_GCM,data:sqoZlrsZ+vyl9WmkMkWfxtxHeWo+2gxjNJw/SsBK8TE=,iv:f5AJvc9hbLcGYyJNyE5dMaAHbIuvBUcuqQlxAHkr04U=,tag:btUBGqhWttojnXPe5SM26g==,type:str]
kind: Secret
metadata:
  name: sonarr-oidc-secret
  namespace: ingress
type: Opaque
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2d1ZiTmxKMmZ1bEQybFhM
        NFI2S2k2ODZkZy9qd1ZSd1AzSUlhcTRZRG1nCitCMXJQVWt6STZUM1Jwc2NLNkZL
        K2xOWWE2TDhVT2FxV1AvdGt2MzJjY1kKLS0tIEJDa2J1OFZuaEVsRGVLTVBIcmRH
        b3psK05jOWVFaS90MTJMMlM5Y3ZFSU0KMwIvNNNcYgY8uLOiddVQJZjVNg0NmRml
        5RYF2/2up8YbSacPvaNIqmMvmTAoNk9aTovh99/vgj4ydk8Xk2C4Eg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-26T19:58:04Z"
  mac: ENC[AES256_GCM,data:dbjFblX/lXeqkYbDUnOTGf7eY5qTQ5qWSUQv4UbmVSbD8/Ui23eHzPwIYgOQ5xa7Ro8m5ZvP4HcMb2j4hRRjTej/zDk6H8x/DSSoi29q5MHXSdyrUVL9uMQmznodASX3lX6Vq/5baiGw01MGE4CgkO9HFWxVynGD7xaQ/5cn3rs=,iv:cE2Rdkg81yDts7eLuBTjJ75lS19qqG/waka6VyEdV10=,tag:b5jqqWu6OfHV+Zo6E60eNQ==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
