---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup-docs-files
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: garage-creds
      key: restic-password
    s3:
      endpoint: https://ohara.infrao.top:3900
      bucket: docs-backup/docs/
      accessKeyIDSecretRef:
        name: garage-creds
        key: ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: garage-creds
        key: ACCESS_SECRET_KEY
  backup:
    promURL: http://prometheus-pushgateway.supervision:9091
    schedule: '0 3 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
  check:
    schedule: '0 3 * * 1'
  prune:
    schedule: '0 3 * * 0'
    retention:
      keepLast: 5
      keepDaily: 2