apiVersion: v1
stringData:
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:KqwIo7lJ2t+1tEZspYV9rqBvgBIGHSoPK3qSDRt/uRE9NkY6QZwC1rOy24a7IeNWoWJ+D+ZFOE40IWkQFi8EkgfF1mOBubdIwMHcVIQRNw9sqI85a5ZGhQWCX7XGmfdgJjMVwM1Olq2XQ46JSapmwNpLpfK7heSZ3IikHFh9a82e5n1R2LtZZTc7dx9SOX+bsLjU8eLnpnCfBDZbqz0lJXd/ax7D0skwQFBnCB+wgNzqzB/KXwuUJd6uT24UcFkbyjP0d50eC/TZ7ExMswJY30kTnnxxMgs+Agy4UB5JjWFk7dft6Fpev9xp+i8KBNUUTF7ncIfhvk5Rs7+014/BvcYhECn4qoKJsJ/fb4VHY67te/RL+Vll9e7q2K4dyaktNSf76bv5kP+bs7D62l5ZRGfzMI1UbrUhOwhbs7waht0vQiHwugYOcimzvej8XFI3vHM6HsoO9kmEFAeeaNR5J2lsijdX/KVBXMTXz9Cvev5n1p5dPSBwzd+KfwlX9P6ORFOW0BI5zbxtl9ajiCGSek4ioWr8a3u4WArOQUgFksmDIHPtSV8DPXgDaxh1yHdw1wcPHatCziLlpqlmnHn0qvw=,iv:I/E7gXM+/+QgnyhGZSbgv9wEfEUCqB3QWRl5EAug2uk=,tag:4272rE9fbIwr06j3VruXAQ==,type:str]
kind: Secret
metadata:
  name: paperless-secret
  namespace: docs
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdS9SV0c2R010T2piZFlG
        TDZPdTZIZC9IQzB1dXpkK1pldzZJV2MweEFrCnBacWR2NTBQQkUwSlVFOGJpdXZj
        ai9iZkhjKzVETmxTU1FhQ2JaemxoZk0KLS0tIGd2YmhpaTRYMHV6cHN1WXRjd1hr
        NWRQUnRYTDAzdWg4d2k3d0hZcDJvMzQK+bdllXr7P3SRt+Z1koeycoHensymrtIg
        FRDAM9TVD6qcChwg/s+4V76dxIoHDziNbiN0MxrXfkXgG27Z4duaMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-16T17:50:40Z"
  mac: ENC[AES256_GCM,data:0oQZeglRSL1ohFhiT+4LQzJtOBOmSja2jYVaLoziGNPswrbJa0xmuA24mR7x+1b+L7xiJwCnPaJjfDpHukWW9GpkNy0Mb+lhMMm13dO9h2BwsRJGDY5hud3YeTVrxFM5i6YCUWwXCZUDwQkR1IZZCceCQO5xAA+Y7tzDpMody4o=,iv:6BGaHajrfgAWhTVOFnBNK/xPdwzCWewehShFwRCwRNw=,tag:YZMWeRi7z4u7V0DgNx4ICg==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
