apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-egghead-infrao-top
spec:
  secretName: wildcard-egghead-infrao-top-tls
  dnsNames:
    - egghead.infrao.top
    - "*.egghead.infrao.top"
  issuerRef:
    name: cloudflare
    kind: Issuer
