apiVersion: v1
stringData:
  SSH_KEY: ENC[AES256_GCM,data:R10iuMBF68FmJOgF/EVcT8d6iTwiBidYY8RfkU8PexUyCc4IW51yua2edYs5IhYl+Dvd1HeATjpETzddVaK7KxzXJEgFJE5lrbvTwLkepy9qEt2Ld/8/Yyr6KFr1pr3wJqomnoIBN+1xCyE1yPa/vBqGY05g4gCO9RD8C5YsSxGQjiOljp2PfTvkffKeQ4m6C2Q4UKKgPxBYkOkcVpXI9PhBXNnYfQ9B5sjl+PDYDRygo5dcw52JTgQc0fCTOgR1VX5kSIM/WeCyAPRrAPpng5/6mw+loTjlMTenLO2omm+puXrPb/3hNpe8OdU/HaZLERBRMLto0aGcfov3vh1KMkqSjNBPqNme5H34T/S6v5S4iaQSGNv7SQe1jNmeSQRt+2QKtFubhpOYiHuCD7Q6iofWV4IfsG0d44ALiNg2XGKyi8Tl8GgYuSBe4+b6jQsPc870tnMrqlavCPx6zrVzQWm4AYILgHZybirZuJw49YG6GLPdiN5yTN7SjCUKuUvRaKjZ,iv:AQ8uTcDo7H8fAWR805RxDZTyBXUFB8ZiEnXn6JIHpc4=,tag:i2BtrjsLDY5Wt1fgK/6t7g==,type:str]
  SSH_USER: ENC[AES256_GCM,data:uO8Pb6OdyC79rg==,iv:y8G0IOfBsPzh79DCQupsJ+wGfUTtD+5hKuCu3OxAjVQ=,tag:uMx4hZwvDZsA7991o7oHZQ==,type:str]
kind: Secret
metadata:
  name: ohara-creds
  namespace: ingress
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTjlQNkNYQ2Y1M3ZyWHhP
        eUtSZWF1Y0ViZnNmdFhRRUdqbWZlcnRMRjJBClFuYzBsRTc5U0owb2tzTVFxdXZv
        a1o0dVkxdUtXTzl5MjY1OEtTaDBTbUUKLS0tIENpajV1c2RhaGFrR3dwNUpWYnBP
        N1VUY1JQSmsvclFITXFwQjBrZno3czQK4NHixs3Qk3e5DkdPE3+w37bU+jRHEJZE
        2bUgXosbuI3kODz7MNhWJp6bfAQdF7ZjWW7C2GrG4Ym8x6C+zN81IQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T18:21:25Z"
  mac: ENC[AES256_GCM,data:AZkhpz4dzJBwvZXnJGfNtwy2B20cETFzEfTakQRsOQLum9Bw4h57c9EN1Npp2J4OTgssubCwvGwmLztZppemdY/sn/wVkzyHwqZzWhEUgDoaPXxOTQT0iSmkVz1i6Ng8TuxyC+9GznZgOwBKcE+b9mfe0+0QHwWHfwx1u6cnpOQ=,iv:7Z/DIIfIqiq9l8sZxCGtH4IvjAe/Iec4KXAqfIiAUm4=,tag:vtgwRGAgGrio6sglyk53YQ==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
