apiVersion: v1
stringData:
  SSH_KEY: ENC[AES256_GCM,data:djf017z5OjG29f5YTyiyFQC0x0aKYzh5PtbLH/qlECTsWyjN+vH7yMVGfBpAcfopT2OneWejC7xk5tUafiQqj6ESOGYK0mvYHhEDTKvURc0phWxTNglT2KdJ0/EluoJcQPC51s80sZoYBruer/Z/bdlBKc0eOeUt0KZH6e+aVpfuwbQEBCMJrg5IWbEU+i/FE9UsZk6RfRM+PiOo+5RP1Ip2w0KcDo1Euq+BPuvv+9Rr3RZYeWWt/3dbOm9kWoh5rjG7DrXjX0hSBrq7DcYJ9OxUpOS9Wy+HjWYkcyazVPTCRdFX0WnkTHs55J65huhLpPc6oT3jymO6UnE0Bnk2SYU7aQ/B1XzlspGuvyk/437fCiqSNYEnSbFxk2B5/NEql0TKP6Fthqn4z8mKMt2a7EFYXDtUk8jhmt1Q+00HL2rzBfhE3GmCVqqYBetvzZX6SdYrgStToEBmBuqzg9sBECRFoPAbNiXQwjaTiqEFP/eDe5k4e1c/4+cw7+69i9+o5f8z,iv:1Q4S0CgI99cGA8oPAYgGpwQH8MQhcSpti+Qd+uJPf7U=,tag:bsMG3ZY4B/0vk+sjLm67DA==,type:str]
  SSH_USER: ENC[AES256_GCM,data:S1aWioOLJ4DJnQ==,iv:Yu2kayPqrHBUsUn/3Mm5shpOBOLrCEgM0aqlFeG3Oj0=,tag:lWJMlGLHkg191V+JGOH7tA==,type:str]
kind: Secret
metadata:
  name: ohara-creds
  namespace: ingress
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJLysrQ1VOQ3NxbmxKSXVn
        OTUra29NNnpTeGdKOHJqVXNnQ2treUxsbFI0Ck1zcm85Sk5Eam1hRWZLTUMvVnRL
        YzJ4cXhZNEk5WDNOVEJhTE5VUVo4d0EKLS0tIHIzUnlrQzF1K0J6enh2akY1V2k1
        MGRoZFprMjA2VnYzOE9DNUxrY1JYSHMK/2N8W9tyGc8SScgYkt7IiWQwNcPg63PQ
        SaCHYwIV5hhpgiCy/Unp51pGlc5RjmWcnVz8znAwuXAqEwM9/zuLWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T19:58:17Z"
  mac: ENC[AES256_GCM,data:RqbTzd3/wE6lbcVoabpsM5gmKLoOzCEV/R7XsfEeqJpVp/S2xQm8wpM2tJPbdogUAjLRuzQufIhWATfDIZ1p+438qzD0qX8qmmrIY7iRFv6DltG04KIIpY9AP9an/jT1smaX9M5d2lbbU4QfRX5txghzpbjGIabPSbkNqFKjvwk=,iv:bXzphuq23GvOCmdPvaLUTUTV68cDT8if+xt71Qrca3w=,tag:Mzpiyi8EgJqLqbbqC7LHYA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
---
apiVersion: v1
stringData:
  SSH_KEY: ENC[AES256_GCM,data:qPJTPI+0C0SZqvdsVV7/VKVztdTMIeDq3s6nEhTLL3CKBWd8nJ/WoVd0n2iDRFdmCy5DB2PQ90vuhT/r/RjI93ygyjWgLDpyd0Wk5qwVHPGDwUs/vDGz7XCCzx158ZItoE2i8bjPVgNN3Go2v39BpHPP9JZJat465zoBrRZLRqB4QPMJValHfpp+z/HzNUQdlSsKSyfyRuZKqlf2tI9JJfKLwjd4M9YymIYbHPynwLUkstiFZe3OC+N1KJrq/bI2+ll8JeNExXQYIcLjwFl3CG80s2xCh0/8I80i8xm+Oxix/qp1fZsjOwjBnWWDlgOUaRpUV2J7PN77Dei4ghS6W9SPDlqMzJqLg0AwbwLj6YNWr7XxDPDTS74l2GTB0eVmm8CiaSPp7bhj7/0BN3+mEzNkLGYA+TqG/apjuPv8g/fd2RtaWfUG5UVtQ0M3HwGS+rZCM3WomxhbOY3j62QBGzJZco3Y/n2GJxElHGsh4PkPicFQGAcd4vhFBGFdRGx9Su2T,iv:3SPWOo473KE42ElPchcVil6+/tfEtIKIAQplqHDpxg8=,tag:ERdTsy2W3a37p7UvkRCvmQ==,type:str]
  SSH_USER: ENC[AES256_GCM,data:NiT/mg==,iv:UnHSS31lqVW6mZ4kSUcvtRQXun/EmMWfzyC/T1kW/UI=,tag:Zq4FC/NLpo6XY20qq7fpPQ==,type:str]
kind: Secret
metadata:
  name: knock-up-stream-creds
  namespace: ingress
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJLysrQ1VOQ3NxbmxKSXVn
        OTUra29NNnpTeGdKOHJqVXNnQ2treUxsbFI0Ck1zcm85Sk5Eam1hRWZLTUMvVnRL
        YzJ4cXhZNEk5WDNOVEJhTE5VUVo4d0EKLS0tIHIzUnlrQzF1K0J6enh2akY1V2k1
        MGRoZFprMjA2VnYzOE9DNUxrY1JYSHMK/2N8W9tyGc8SScgYkt7IiWQwNcPg63PQ
        SaCHYwIV5hhpgiCy/Unp51pGlc5RjmWcnVz8znAwuXAqEwM9/zuLWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T19:58:17Z"
  mac: ENC[AES256_GCM,data:RqbTzd3/wE6lbcVoabpsM5gmKLoOzCEV/R7XsfEeqJpVp/S2xQm8wpM2tJPbdogUAjLRuzQufIhWATfDIZ1p+438qzD0qX8qmmrIY7iRFv6DltG04KIIpY9AP9an/jT1smaX9M5d2lbbU4QfRX5txghzpbjGIabPSbkNqFKjvwk=,iv:bXzphuq23GvOCmdPvaLUTUTV68cDT8if+xt71Qrca3w=,tag:Mzpiyi8EgJqLqbbqC7LHYA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0