####### Postgresql
###
###
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-immich-backup-store
  namespace: immich
spec:
  configuration:
    destinationPath: s3://immich-backup/pgsql/
    endpointURL: https://ohara.infrao.top:9004
    s3Credentials:
      accessKeyId:
        name: minio-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: minio-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-backup
spec:
  schedule: "0 30 4 * * *"
  cluster:
    name: immich-database
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
###
###
##### Files
###
###
---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup-immich-files
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: minio-creds
      key: restic-password
    s3:
      endpoint: https://ohara.infrao.top:9004
      bucket: immich-backup/files/
      accessKeyIDSecretRef:
        name: minio-creds
        key: ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: minio-creds
        key: ACCESS_SECRET_KEY
  backup:
    promURL: "http://kube-prometheus-stack-prometheus.supervision:9090"
    schedule: '40 4 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
  check:
    schedule: '0 1 * * 1'
  prune:
    schedule: '0 1 * * 0'
    retention:
      keepLast: 5
      keepDaily: 2
