apiVersion: v1
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:LeypE2z47aaL4tivJw==,iv:GnDGwIukvxhn2kBxHImFH5MFTMz7x4vIvoHlsG32dqE=,tag:8Hv4+DV6RfK6L2PNF6hcFQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:yVhCQuPDZTzmgsKF4DvK2Q==,iv:f8zaU54AF3HjB19J9G8fmiKdiY9QdycyWr9G4BUAe7s=,tag:+Sqq8jCXhq38yAz8LWDzvw==,type:str]
kind: Secret
metadata:
  name: minio-creds
  namespace: immich
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvKzdjY0RWVis5dzVCVzJE
        elVuSVBvVjV0dytQR1orOVNwenF1czFxY1VzCmdtanpZdnNMVThOOUxwOEtvWHFF
        eDdUMk83OGwwRU5ZZmdZMzNTRXczSGcKLS0tIGxsQ1N0amUvWEIxajJFSGVsbGxr
        QUMzQ3Q0Ri9GamxaamNrcTkwcmoxUVkK9XKL57/8Rx1Hh8pLn1tl8X7262g++B3u
        5+N/pf1zEbRmsy0GvJVKrELayFvO3gdVYJk+Z9SP5ukAVNKQhWzmpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-11T14:07:50Z"
  mac: ENC[AES256_GCM,data:brsoksN0hwR6PC2QDG0XI/1ISzOAUakFXV5Yq6OIuTrLC7X+pMBf0I0CR4RbPv1108fQ0cA8IxZMDX7+axe00KNBgQyWAvTZ/xL+SyEX2OpFntxr1lhxWwD+atXyegJ4kPRDyEDb0JdRQ3aXzON6JZXTbqTgbx9P5tJnDrfRhRU=,iv:adfkx+WuD0l8rT7fal5D1z+Y2tOy+QTdZLCaSQHS/XQ=,tag:XNp9a2LkML6j28x6CThF5Q==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
