apiVersion: v1
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:j4o8O8r1pITJFVNLKn5haYohoGbD0wduhJ4=,iv:j81WhPLFrXkYwqOGurNDL9u29SOb8JLS9l5NJawM2CE=,tag:JL3pcU9Ul2FsV2Ex7TEqIA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:YegR6tMoZU/G3ArAui7gCy5jgAnTkA2OCGMY2N8azTqMa8wCtO/Wz4oU3b5osWgqKccv3jT4ofy45O76d5VVKw==,iv:NWAn90FjNuPcYVhf4qc6DYrpLWVBQoVR9IyLaV1C1X8=,tag:1BCSL3e8V0dmu0kJG529Vg==,type:str]
  restic-password: ENC[AES256_GCM,data:NTUisxwwOH7ZXaejY8HtWw==,iv:EYnRjTnrEsXt5e8NqAZD+PTmZUy5dmydZUPGffE52Pw=,tag:MgC48EDiu1gu2wSIW5pK8g==,type:str]
kind: Secret
metadata:
  name: garage-creds
  namespace: immich
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveFFmV3I0ZS9FYkhDM1ZQ
        YmxseUFLeGVxT1AyRUQ2VHBKYTFETFplaWlrClk1RmtROFp5WDErMWVIQzQwUDJH
        R1cySUl2eWxxYUp5K2lLcHlLSFNKVjAKLS0tIFRHV3h4djU0b3RXSVV0NnFrV2xP
        YndBV2JlL2FGWGFxZDl6SkVaaG1makEKG/4lD3UbA8nCjWtJdYOCpIFgUNKxVGyO
        PgqnGLiI/tpD4DnZaD7t/DArGodcmxMkGkeIfLEgAMyKq13PDjg9jA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T20:02:38Z"
  mac: ENC[AES256_GCM,data:ObJIAMqimKtM/Qu/Nw38P7EkQ8e5R5yLoGmdLQOw6ETv4zWcGkvoDiugvBuwC76safp0R56YNRifQzr5B75QgW+c6r3BjJibKhLuJc4PmAeBp8KRm3wz8aL2zqEnMUvInfsep0sjm4H+tfAlTgMLb7FMb0inUTwAvKaZdtA48lI=,iv:cWb+7GIiqRPVeEksoDfNKZFHToqHL1KIdBwIXD0jp5o=,tag:YFcvf2LM/i1ovMglkT3YAw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
