apiVersion: v1
stringData:
  immich-config.yaml: ENC[AES256_GCM,data:pKVhc7ightaTvGzXHTRrif1VSpSj+rajC9g/wXtEr8FX2esRAF+yiXnUt/MT4rp8Qdt4zhYRl5C0Nb0QtnZGkYtsGiTlEsX6TUa9r5aFkt7Gb40jugRhOvIVkbzw5DGuazNJySPjUXhq81LMIBwa0suToHkif1/smdbrf3CcqXcjcctWcniV8syEaEks7RDSrwHM+as9Zzmy7TGoPJ2YEX2zVLKN+P2TdKc2oF9xkuipXg/4GOOUquwJWtlgUlh+9F/sNaqC3RGn00Fx1HdUq+nA4wbo/AmWEvuOwv1bmWjIHSxDbrhXN50XPOxeJXZ+l89jmN35Xwjora3/J2Uz+LMmARgah7P8UogZHTWhotcjP85m4Cn7gelicQgBztkrJNOotshRtSeotKQpAH0j9f6W9EQsgXBp6A4PkmLGP4VgwtZuHzLShGrjpM9vD0N689+FX+nqawy964BoBAOplSqsqm9gDFmcRBUYKLfUFVmYw2ZH91RzLfwmV9NLJqHaHbQITg==,iv:gIHqPwjWhrwb1qrHnCSBA+xx4yqP40eGmBZ674iM+ys=,tag:N4FruzORTlSgE8pJ0rumjw==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: immich-config
  namespace: immich
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT3hzZDViVm84UEtJZGZY
        RlJqUUpUL0lYZ1JHY2NiSHJvUWhGRVYyQUcwCnRuZHZYMHJNRGtDZ2pzU1pJMzRJ
        M3FyV0NEMHp5VlFNTy9kYWY3dzBmK28KLS0tIDR2MHNrRFAxdmwzSENBWHBXRUJ6
        ZWR3NzJueFJnOER4OXUzNWtmQUhBSnMKUXkOq5dNsJgg5UlKTji8jPBpKC5qA2MG
        TaHcsX/KtRbCRgBHXjYIyiO3stqbjgUHj+gdOSgcIE9AROWhGA9aYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-20T17:50:55Z"
  mac: ENC[AES256_GCM,data:6KMX7NRIdnRw4t46vZvCBwcacVzSSpWnRPBs8uWCiWiS7GthFDy/Fsb8HcW3hRJudVHEoKXaH1vYWdCR6a6LVWiQjRWbqhhp8HCQMOXbNTXHB+qx4V84hyGIdsjM7aEBK1wHDubzt7OO52K5Oo+o00qkF8iQDnaRsEltP/eiFEo=,iv:wR7FZd8ppvZQXn1jO9itJi8xKLZ0krldCuyXy4J1Z0A=,tag:sICZzxp9DskPEA/vs+BC3g==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
