####### Postgresql
###
###
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-romm-backup-store
  namespace: services
spec:
  configuration:
    destinationPath: s3://services-backup/pgsql/romm/
    endpointURL: https://ohara.infrao.top:3900
    s3Credentials:
      accessKeyId:
        name: garage-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: garage-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: rommdb-backup
spec:
  schedule: "0 45 2 * * *"
  cluster:
    name: romm-database
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
###
###
##### Files
###
###
---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup-services-files
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: garage-creds
      key: restic-password
    s3:
      endpoint: https://ohara.infrao.top:3900
      bucket: services-backup/services/
      accessKeyIDSecretRef:
        name: garage-creds
        key: ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: garage-creds
        key: ACCESS_SECRET_KEY
  backup:
    promURL: http://prometheus-pushgateway.supervision:9091
    schedule: '0 2 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    podSecurityContext: # For pocket-id keys files
      runAsUser: 1000
      runAsNonRoot: true
  check:
    schedule: '0 2 * * 1'
  prune:
    schedule: '0 2 * * 0'
    retention:
      keepLast: 5
      keepDaily: 2