apiVersion: v1
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:YrqxhmdxIRfGX+CysmzD,iv:G+fyYPbYkS+ZWgfhcZ+AEltj3NUV3w9avXSfYAbqzS0=,tag:Uqy1GvbrkHpZb63NNXSbpg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:21/L0hQRd5ff8qWK6XCPpQ==,iv:Uv2Kzi3BzMGm7e1dR73IewWtWNALkGlecterjsU/SQM=,tag:H50RadIpFgR0JYOZ1rnsJA==,type:str]
  restic-password: ENC[AES256_GCM,data:D6DnD/9PrFvVDXxhNBfcOA==,iv:ngXowTX+yT/Ui+lx1QbxfR/rjftT4qA4vHZ+Ylq76Sc=,tag:IwqwCIyqymvQq8rH6eecvw==,type:str]
kind: Secret
metadata:
  name: minio-creds
  namespace: services
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNzhrcHdWTHQ5NFJkLzV4
        Wko3UlN3NWZmVjljdUp2anVBVE4wbW9GTmpNCncrVVV2TU9Ga04veTZndDZiZnhF
        THJHb3c4dndvUFIrRFFaNVdqam90V0EKLS0tIGtUZnpSbGUvSTNHMFJvMmQ2aTJt
        Z2xKMUdtZlI3bVM1TG5QajRmQWRxazgKdrzYi3c+cbE+nohH0eJpiSuxLmy79nME
        UtFeMWefra4+42HW/9pxpOOHQwEVODRtVX7a33uTCyS5fs/XzzleZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-12T16:20:35Z"
  mac: ENC[AES256_GCM,data:yUYyN3EkGPKmAAs+3U5dX23sMkzTiX23Nmyflays7lY9pwgKMkYxgVNBn1MwHf3UPEQ6hY8PqF46AFVDxy4B1porVG1ShCM8wDKOtt6zu4gaDF6Pzt/cyLWGJLlsAiPtjp0/vuN0iLbJiMMteoJhxSJSdtB1l8wxI6uGI1EXSJs=,iv:gyrBj7tzAGj0EpgJZEdcaJkxjHyj3BeSAZcSP3WpINI=,tag:zniLVLtAhsVco0bpJEq3Fw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
