apiVersion: v1
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:uNDnJR85Gz6xdq/rPyGesQZIKHDr5746/ns=,iv:yo9hgdGQ8rjsnpS0sreEs7PiZgDurjrvm8HkIdmKIfs=,tag:vTXVwvysYLBrgjV1EJ/DdQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:/KEDI8RFzcUd9nghW4eqYkNsFnWLBIC4TX0sLWos6spqp3nKb+iA/r0Dx5rUk0VbpcyzLT156m/GSK8NWp0MGw==,iv:ucC5JWw22ySCvNGI+oydb/acGU/fFqz3U62raYcV7Ec=,tag:1LsikB0bahCqwqiqv38EAw==,type:str]
  SSH_KEY: ENC[AES256_GCM,data:+f6/ARb+Xczwf59XrWf0pGL+39BuzigrRKFDmjjc3VmkclhIudYXczGhedjIMmk8u/Z9oTCVJKPCHCq5h7WKAqLT6RhFRY3R+VYx+KvQFjrUPYVQJz0xmQKmY5wi/pr7cLd2hIuxZHyeBcRyJPJpaWfSbX+zrCtaQqxSgTFSqzGb65wC/rscYpiVetnrJy7Cwdoe3DajdHS0OLi93oohauVz7BaMVKuJwF0trMVBvbQv4AqNMqFEx9mYUWy9kOzwDIB3EdZaJxUNbrzDVbXDptIdnXXggmPKLKbViQ5VQ0uYA42qFNfxXx3AZSs0/7kFXqZKKq0Q/rnOanHItZl5b9k9d000z5Rr5h+TxMClv9n/HCxLwWlXNWAXCOSXNrKuFd8GcqU3HI0DAM10xgkpvreNLvBkp7+PqNeBgnR3jYLMCF82B15CwGHDt0zgHO/mJcsGimDbhqm+H3KQMg/YY+tj9sH/b732UL+lZ5H8mv2CuW26AL2upaUZF8QKSOcP7dBqXQ6ExckBGyKzt8HegFcWtbfPaXt4tU/VqSSlAROaxUQ=,iv:yTSXLGpIjkdMk56XAYQIneSXbsr6RtnwSysDgMq14LI=,tag:qeEN0sWhbpND/lHiuXY+0Q==,type:str]
  SSH_USER: ENC[AES256_GCM,data:N2tBAg==,iv:DCYU/F3FhdWuhwRDMgmx2lLz+oK5yV6X7YoFI3uH6Jw=,tag:ZzCHulpjXsyivZp5cWS41w==,type:str]
  restic-password: ENC[AES256_GCM,data:a8Sv/6efPq9VohsmJSNCZL1VmEm4QAmRrhdlpzbTJYA=,iv:FoTHVgTubLC7pg53TW3MD3Vhju1PQ1W/ReNses0Mv2c=,tag:Kjr3SsOxfsRoMZjO+/uWHw==,type:str]
kind: Secret
metadata:
  name: openwrt-creds
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFN3FxZlNDQS8vZEtiRHg0
        TkRjeFZ1YnpiYythN0thbkZ5SEgwTCtncEJjClZjT0h2SHEyVjlhVUk2V3ptSkVt
        OUdPdFBqVjFMbzBCS0c3eU9meUZUOE0KLS0tIDFrR3hKb3hKdDFaYXBHTFpLMkJX
        dlNGWWFOUENIeDRqTnVVWGJ6a1RJK0kKp2suBkS4VUtVtwjTqVQvD3+QZ97YRb7e
        8pXY1mnZT1KqihqK7Wv0UNCmf0LydQ8RJJU6yV8UdynTX6bYu2yp3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T20:09:26Z"
  mac: ENC[AES256_GCM,data:flrsaqzmViALkFAAbt/uQ05OXFQtSf4fZiikRRaPWhFbHsCcoPgs0SNW7ttvPLChQpcns2m5CRNN+S/Bi1U0UInpm9mXKa25RMk5zpcwc+oh7y3yExJkMQNtODbHql0/zp57bR0csOCW0w2OULqb31SV3p8baUfXSqBoWt0DhyM=,iv:ys3nnm7YZhmyIWsXr0+fnscmQzAagfpwMI4EKulty7I=,tag:0pllW6/XpqtqhNIb28Vh5g==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
