apiVersion: v1
stringData:
  encryption-key: ENC[AES256_GCM,data:p8pD1Ks402dpIEJrFEOz27KjTqijpygTXrPJ4GDyqdG3ygnjoZrDiawseuc=,iv:dxUrJtwoS0OGP9e7WO/68sHOjvOxWITpuESUOVSPDlo=,tag:N2KWuA6FAhIkTJV/fRlLOQ==,type:str]
kind: Secret
metadata:
  name: pocketid
type: Opaque
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SERXeGQreit6OEE4Njcz
        K0tCUWorWnJsZGV6WjNvYm5lRm10TFVSTjIwClJOYnZPQlo3QVNnNkI3SklmZ1NI
        UGdId0NhTzU0OXd2WjR1VzcrUHFHUFUKLS0tIHRJcHVJOWoxZFpZcktZWjNPbGVa
        ejJWaUN6UjBDYWVCK0VsWmIxQjdzcUkKilwuGZabChevqPQu2RSqbFmDyNwWIHdN
        DJwBg+6/xB9TXZMT2IOimhmFLDlYS6jUSAS2nfC1D0E5JihPQhm+Qw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-14T16:19:28Z"
  mac: ENC[AES256_GCM,data:4xBsPvCeMCSFyRMxmknhofVT6Eh16s3TL6xrLPad67gx/Zx6CBMfb4nJsVKbPFVWTFSV5cbczkqT4754FGymB1m3xFqMD/VCWWyeVBu+31JDNGeW7vqhpsYBDzpNfemfidkjbcKPKbPm+42iryiZFVTPHwndDVfcbalppulUjZE=,iv:lbcpWJiR24mAyKHaysEIq/ymDOzfx6xTN22aZMZeucE=,tag:50M5u+yUq41RJXGn+o9ESg==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
