---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocketid
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: pocketid
        image: ghcr.io/pocket-id/pocket-id:v1.14.1
        volumeMounts:
          - mountPath: /app/data
            name: pocketid-data
        env:
          - name: APP_URL
            value: https://pocketid.egghead.infrao.top
          - name: TRUST_PROXY
            value: "true"
          - name: PUID
            value: "1000"
          - name: GUID
            value: "100"
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                key: encryption-key
                name: pocketid
          - name: TZ
            value: Europe/Paris
        volumes:
          - name: pocketid-data
            persistentVolumeClaim:
              claimName: pocketid-data
        service: 1411
        ingress:
          domain: pocketid.egghead.infrao.top
        pvc:
          - name: pocketid-data
            localstorage: true
            backup: true
