apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:M5+68UZH9MFy5vb1d9ELOafaPr88/eb4mpfpiJd3R7Vj/fcwms/uGTydQutDobYqC1Gqrgb5N7HxQMIUytNi4gDRn14X6F3Rj+xJDn9u5ZKzc541mw4ThC2TQ1pj,iv:GyUx1QGLngee3ezLUkv4Z1L3RJ4CmDLSmT9Ds2V9vco=,tag:bmom7vAcURGZmeKw5Gm+uA==,type:str]
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQlg4cDQ0bVVYNTRTSFZk
        R3ZDRW1QSzVDaXRmTUQwcjJBRXM0dEtpY0VzCjVSZVM5QnZ0N096T1VDa2JRRnh4
        MVVoR2NHRVlhZlZzQ2N2K21VOExiZGsKLS0tIGswN1E3S2ZrZEVNVnJ2eFlRdVkx
        M1hjYi9UY2REcXh4N1lsZkZwZ05CSFkKkaG+dC7v75WL0oLdsY04KJROm1GluSAc
        lyzI9E9W2jkNz/niYsXlPNxKcjUwrLOFJqDjSp8qRXUX+qna+Mz6Ug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T13:28:10Z"
  mac: ENC[AES256_GCM,data:IBA4xCqqK8yz2zQm4/jpav68noF2tlzMIsl2ayhucDo+X8CCeJECSyLZ3bASmDQ6Vo7Sf2ts9OlAoyC9byxLYAyXLTc5ITMknONLlPApe7MNs5x5djiIcqmWrpobNh2bYfQwU4B9Kh0oLDw9tEWXNfKtKX1fuSc/kYhKxJOHJnU=,iv:nVTtfpzS7ZV2owmeZYO247a+1pSkk6efA3v+AVJafgM=,tag:gN4kqThNzs92B9Atl2sg+A==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
