apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:kqst0GteO4t3b8MF7Nb6QNUzBPEDv4WOZHtwNh+Jc9C8M9MUrwHddS1D4nxha7L3SL1fBqH8uzn9gJkoH6Vfnl5ai9EXpOg9iMb5t1A7P9i4NB4/WEr5Ed8LgXrF,iv:YQZsJE82/E46iyFu9lJ9mN/MYp9IbW9Oq+EGZ+NFiUc=,tag:g6WNJzmktQdc6h5D2q9/DQ==,type:str]
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Vnp5MDBwNnVNVzBOT2VL
        QkRhMlJUWnhJTjQyUEljclJTbUgxUDZMNDJNClk2cFdPcWJzZVkxQlVZNU03Ulpp
        ZldEWnVFVzZJVHErU0RYNHpFakRyYncKLS0tIEszSUlXYmpIYXhWVzBkemlIcStE
        WkZKVUQxSWkvRThDK05kWjlWNFV5UE0KAPNvu+jl5rjwE8BFJBSOBwYZj7DZRikt
        0I6mDsVJroRibLMWDgW0H4sPJl9bhU+lTtiMIAm0misKXRP9pF1PUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-19T13:33:34Z"
  mac: ENC[AES256_GCM,data:4WG2WyKmB882m36iAqoNJi/wSu6ruIF9jxtZdRNIcvWVS1zAatoyqkbd9cfRKuVjDdUhz6iNyYA5e5j8Y/u6/cWY3A9BRQJujYgeWU6G2f5e3OXlLvsUocWaVlSeH4WR8blr8Ck7djn7fj8uXqDwHdZClSD1LhwSBnYi5DinIOc=,iv:0ZW5VBWDh+na397/aetBV8UgwMd3rV5aBVbP6nJ2Ayk=,tag:Ce7pcc099nZxjpn8lZ85bA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
