apiVersion: v1
kind: Secret
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:hVgl52DE1R1VJZTYUEnjWhhmnqOds0m9clpUdyllbYee7HCr,iv:mP9fgxU2JxsoXySkydtUza3EsU9uXeBSPe+xwEBA9Es=,tag:9WJ6+kJ09nLhz7ul3HcBpg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Le/q3MxBvSXuXyWgrmfBLC+1sYJeZQ1p1bCc1VgfziI=,iv:D9MHTYpdlq99KFUJ3onfYmnBQ2LvO9GBUxNzx+MT/hI=,tag:C92Z0hZDobueTJTexY+X7Q==,type:str]
  RETROACHIEVEMENTS_API_KEY: ENC[AES256_GCM,data:arBE9OnXV6vZNUo5QCcGEl4QJ+whknFRkyKhDA1JKF4=,iv:oEZk1ii7SzvXmeRBge0PHfBviNqZKZpQIcJlHij6aQE=,tag:8Vhk8kmxrjiysWYQezYK8w==,type:str]
  ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:Iy1iDFoHY9oq4jP+b2bv1NIx9nU5UuF7M73/T3E/sLoHzB4XeJzPaY0yBG/fehp3umSauWsZQOtxogzIn0TZFg==,iv:7PRfmq1LbfLMklkHIBaN8osHFIPHY3+4PZsPTIHSRzo=,tag:tn5smvy8Y6q8yiRttmtALw==,type:str]
  SCREENSCRAPER_USER: ENC[AES256_GCM,data:DjLAn+K9W1ypdfHv,iv:/ves25KNIROX7euG0C59ZsAcP1kIcc5Kcm9hLt1r5vM=,tag:fh2daH9SYlFNrvqA/6vnpA==,type:str]
  SCREENSCRAPER_PASSWORD: ENC[AES256_GCM,data:BCAqveFj4+NK+bOPedIKD8Y2OXI=,iv:GraA7ZHngMSpWTnu3vjHpTMxbB9A0sSW0oibeuZgEJA=,tag:l7xD39IIAvG+1KC+zG+cpw==,type:str]
  STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:tJS6s0y5gTJY0ALFC9xZGSBZyPPrOnVwMhrilQAeZH4=,iv:mtFYIaofzeMQo9P9Y/GevxsVJdBbpuJMrPfXKZVC1yc=,tag:SotjYh+vxE739Y9DSVdDIw==,type:str]
metadata:
  name: romm-creds
  namespace: services
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTW5kYVhkSUVhRXRSZTlt
        THF2c2hPUkF0UHM3YzVGcHdSNnd6RnBSeTNVCktmcWNRK0NyS2tpZlRsOHhIVmlT
        MFdYWC9zSFJxbjJIVHdnYW5pWXVENWMKLS0tIEdEVDZZQ2RjQmcvVEk1cGpWcUo5
        VUM0T2NSOE1rVDFwWkptUHBWWDVoT2cK50Y1ivyhw5omLuUlE/fd9vUWrfYvBJZ6
        /4WmlYr3lCBrRIWoqJsB8R5lNP7UL1gMVQ+7aVTC8y91JeZVx0Lbsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-03T10:39:32Z"
  mac: ENC[AES256_GCM,data:QxmN8rHElLyDt+T3zUAG3YaT6sutd1EpUrFG9DeEI5An509ISWYlCK82lDxe/jk91yKOh2EJ1QDh1zG8ns8faKNq+GTSIsmlbXoFUdZGWHhTgwmQbe4riMMhNhACVr957+A7iRh2MyvcYaeANQKAv6816V9F9VkpVJXJKHzOyOI=,iv:LXBlQNF+XRdYOLdV98AgMPyxksdXTRK+j0RdLGfSrAs=,tag:3wPKGn84yOoWgP7K8LYIkQ==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
