---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: romm-database
spec:
  instances: 1

  storage:
    size: 1Gi

  imageName: ghcr.io/cloudnative-pg/postgresql:17.6

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-romm-backup-store
