---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-library-root
  annotations:
    k8up.io/backup: true
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: ohara.infrao.top
    path: /mnt/raid/romm-library/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-library-root
  namespace: services
  annotations:
    k8up.io/backup: true
spec:
  volumeName: romm-library-root
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: romm
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: romm-valkey
        image: valkey/valkey:9.0.0-alpine
        service: 6379
      - name: rommapp
        image: rommapp/romm:4.4.1
        podSpec:
          hostAliases:
            - ip: "192.168.8.5"
              hostnames:
                - "pocketid.egghead.infrao.top"
        containerSpec:
          readinessProbe:
            httpGet:
              port: 8080
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
        volumeMounts:
          - mountPath: /romm/assets
            name: romm-assets
          - mountPath: /romm/config
            name: romm-config
          - mountPath: /romm/library
            name: romm-library
          - mountPath: /romm/resources
            name: romm-resources
          - mountPath: /redis-data
            name: romm-redis-data
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: romm-database-app
                key: dbname
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name:  romm-database-app
                key: host
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name:  romm-database-app
                key: user
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name:  romm-database-app
                key: password
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: romm-database-app
                key: port
          - name: DISABLE_USERPASS_LOGIN
            value: "true"
          - name: OIDC_ENABLED
            value: "true"
          - name: OIDC_PROVIDER
            value: "pocketid"
          - name: OIDC_REDIRECT_URI
            value: https://romm.egghead.infrao.top/api/oauth/openid
          - name: OIDC_SERVER_APPLICATION_URL
            value: https://pocketid.egghead.infrao.top
          - name: REDIS_HOST
            value: romm-valkey
          - name: ROMM_DB_DRIVER
            value: postgresql
          - name: TZ
            value: Europe/Paris
        envFrom:
          - secretRef:
              name: romm-creds
        volumes:
          - name: romm-assets
            persistentVolumeClaim:
              claimName: romm-assets
          - name: romm-config
            persistentVolumeClaim:
              claimName: romm-config
          - name: romm-library
            persistentVolumeClaim:
              claimName: romm-library-root
          - name: romm-resources
            persistentVolumeClaim:
              claimName: romm-resources
          - name: romm-redis-data
            persistentVolumeClaim:
              claimName: romm-redis-data
        service: 8080
        ingress:
          domain: romm.egghead.infrao.top
        pvc:
          - name: romm-assets
            localstorage: false
            backup: true
          - name: romm-config
            localstorage: true
            backup: true
          - name: romm-redis-data
            localstorage: true
            backup: false
          - name: romm-resources
            localstorage: true
            backup: false

