apiVersion: v1
stringData:
  SSH_KEY: ENC[AES256_GCM,data:G1gg7yWBcK3BXsqS4TUibSMlAA6wR0pf4dpcXRwqhXZIMQ+NEs7Qn+L/vu6M49iDdmN2ylE036Mn6zcFz3F2N/m+d9gqqCKSNDkfhItlAgf3Rho+dlAZhSLVkcs54ZG7dv8RM1Zi8Wuk22/d7ywwrZCUAVoMuehOTcY1RT9pLXxYhqvHC6Lqw6XeSkBuldus7JzysRI5rgncSQgh8/sF+s3x4J1eXdmxnOxr2OBDgvtrMFaavZIb49qlKijp26BLqku2UHvKBaLiZPBK7j4Owk7BI3Ddluih7f14fu2FhqxRq+NKQiS2mQvqismODUJMR2Rgjr/JeouB0h3cBNxQtGLrgFNZVTOmr5ZFxu18XtOto/WHfeKNdO6YMy+I0mXWVHkxUYm3kRUS6qK67o8GtdFRnnt9vKGvPPYgYuD7K950xSBytyeuF5KZZ58iWqSanEbSvSeSJ2jJPqeU1eOhreozX4SldOc0lXSZGPTcPvq0egPssTBJHv6Gxl5eQNnjh8nY+/l+D3C6T+UvVDVbjLTBlm7cyde57VkH8Hyo+pdWbOc=,iv:ZRKz1/Cm0PtEHz6ym/oAwkSx7u85pD4eHTeaUgXX0SE=,tag:vg/ebJt6yKOrpu2QyTrzww==,type:str]
  SSH_USER: ENC[AES256_GCM,data:LV+o8HNE45UR5U31Iw==,iv:LPfBJBBlD4J0q9RiOg4wSnqIg7anOlqREOFgSprSNOI=,tag:2qyN1hZLOb/UT9P3bx4Qjw==,type:str]
  ACCESS_KEY_ID: ENC[AES256_GCM,data:QJEV8diR98BqcgiykgsO8YzOIPg4n1XOMqQ=,iv:kmPNLG2RK3rBEOywKpzz/OA9GhwSgQ82/W/fc/MpWGo=,tag:E4+UJzP4trXX/7QRfYmzkw==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:SjrvEEXsAtcqz3iyPkRheQeJcUs0gqgNpRltIX4dos51jpDfZm1O8PnUTa670pckd6JPmjO6SjsF88E+DPCq7g==,iv:K0QAoZuuUeoK6gX2NOfGmQNLh1wfzbRauDjSojAFGSw=,tag:qfBsiErdAaBppO6uGpQ+Uw==,type:str]
  restic-password: ENC[AES256_GCM,data:F48TPcI0wHsQDapPb1QnUyCey0W6KWrM9fGHhK3LhVA=,iv:YpqlBcOWdWlWsh0d1QA2B1xQWETSCDrhaa4GHHm8p48=,tag:z63yjUKoCN2LUbzMvgbX4Q==,type:str]
kind: Secret
metadata:
  name: skypiea-creds
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOXErWDNZV2VFSnZlOEZy
        UEZqTE0vL0JLaW1BMnBZWGFzeHJpdzc5d2pBCm5JcWwxL0EybUNGenEzcGtjUzhX
        U0trdm1pODhXaHAySE5DYmp2QjdrM2MKLS0tIDRDNDB1bm9LTUdZWXNVcG4raDZ0
        aHBNMzdYbTZ1R3dEVlpvbzVhVnk0VXMK4oATBu5VZRQ38eRvDFmcYX8IXpZHG3KM
        CoXJsrnSI738pe7o/oBVapAMNPb3VEOceXkqYC/aeYX24E8+RnJklg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T20:19:10Z"
  mac: ENC[AES256_GCM,data:kx43+6RNQIzJBTYRkwstpKw55GTm14OPMRPYmA8I+FsrQ80TLN9ECX8nAf23qpbq06g0JA26Dtu6CDoC9ALUS9Xd6uC4DQklND2ge2NpJhS6yoY/sQyAlE+l5LFO2C5z/3c/kRNo1ZfRUvHXjGHBbfbwSET0y92ooEHjn2NIUUY=,iv:Jl9uCel70Tld+cpISP/SkAkD7UXgKTLaVH6KBhNBikY=,tag:CAGZWI30kXVayDGkL+T6Fg==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
