apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 24h
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
spec:
  install:
    createNamespace: true
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: reloader
      version: 2.2.5
      sourceRef:
        kind: HelmRepository
        name: reloader
      interval: 1h
  releaseName: reloader
  targetNamespace: kube-system
  values:
    reloader:
      ignoreCronJobs: true
      watchGlobally: true
      deployment:
        env:
          open:
            TZ: Europe/Paris
