# this deploys a GitOpsToolKit kustomization
# for each folder, in its own ns
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: media
  path: ./k8s/apps/media
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docs
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: docs
  path: ./k8s/apps/docs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: services
  path: ./k8s/apps/services
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
