apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 10m
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 2m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      interval: 1h
  releaseName: cnpg-operator
  targetNamespace: cnpg-system
  values:
    additionalEnv:
      - name: TZ
        value: Europe/Paris
    resources:
      limits:
        cpu: 100m
        memory: 80Mi
      requests:
        cpu: 2m
        memory: 80Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
  namespace: flux-system
spec:
  interval: 2m
  chart:
    spec:
      chart: plugin-barman-cloud
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      interval: 1h
  releaseName: plugin-barman-cloud
  targetNamespace: cnpg-system
  values:
    additionalEnv:
      - name: TZ
        value: Europe/Paris
    resources:
      limits:
        cpu: 100m
        memory: 40Mi
      requests:
        cpu: 1m
        memory: 40Mi
