apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  interval: 10m
  url: https://helm.mariadb.com/mariadb-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: flux-system
spec:
  interval: 2m
  chart:
    spec:
      chart: mariadb-operator-crds
      version: 25.10.2
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      interval: 1h
  releaseName: mariadb-operator-crds
  targetNamespace: mariadb-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  interval: 2m
  chart:
    spec:
      chart: mariadb-operator
      version: 25.10.2
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      interval: 1h
  releaseName: mariadb-operator
  targetNamespace: mariadb-system
  values:
    webhook:
      cert:
        certManager:
          enabled: true
    certController:
      enabled: false
